name: Sync main to develop
on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge main to develop'
          title: 'Merge main to develop'
          body: 'Created by Github actions'
          head: main
          base: develop
          branch: main-to-develop